name: main

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: docker build . -f tests/Dockerfile -t tests

      - name: Test
        run: docker run --rm -t tests
