name: publish

on:
  workflow_dispatch:

jobs:

  sdist:
    name: sdist
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: setup
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: deps
        run: python -m pip install -U pip wheel setuptools

      - name: sdist
        run: python setup.py sdist

      - name: upload
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: "dist/*.tar.gz"

  wheel:
    name: wheel
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: [3.6, 3.7, 3.8, 3.9]

    steps:
      - uses: actions/checkout@v2

      - name: setup
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: deps
        run: python -m pip install -U pip wheel setuptools

      - name: wheel
        run: python setup.py bdist_wheel

      - name: auditwheel
        if: contains(matrix.os, 'ubuntu')
        run: |
          python -m pip install -U auditwheel
          python -m auditwheel repair dist/*-linux_x86_64.whl
          rm -rf dist
          mv wheelhouse dist

      - name: upload
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: "dist/*.whl"

  publish:
    name: publish
    needs:
      - sdist
      - wheel
    runs-on: ubuntu-latest

    steps:
      - name: setup
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: deps
        run: python -m pip install -U twine

      - name: download
        uses: actions/download-artifact@v2

      - name: sdist
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: python -m twine upload dist/*.tar.gz

      - name: wheels
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: python -m twine upload dist/*.whl
